preset: psr2

risky: false

disabled:
  - elseif
  - single_blank_line_at_eof
  - single_import_per_statement
  - function_declaration

finder:
  not-name:
    - "backend/_ide_helper.php"
    - "backend/.phpstorm.meta.php"    
