dist: xenial

services:
  - mysql

language: php

php:
    - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - cd $TRAVIS_BUILD_DIR/backend
    - composer validate
    - mysql -e 'CREATE DATABASE thread'

install:
    - composer install --no-interaction --prefer-source

before_script:
    - cp .env.travis .env
    - php artisan migrate --force

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml -c phpunit.travis.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)


