language: php

php:
    - 7.1
    - 7.2      

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - cd $TRAVIS_BUILD_DIR/backend
    - composer validate

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

      
